require: rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'Gemfile'
    - 'db/migrate/*'
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 20

Documentation:
  Enabled: false
  
Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Lint/UselessMethodDefinition:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

# Rails固有のCopを有効にする
Rails:
  Enabled: true
