version: '3'
services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    command: ["entrypoint.sh", "rails", "server"]
            # 'bundle exec puma -C config/puma.rb'だとうまく行かない"
    tty: true
    stdin_open: true
    volumes:
      - .:/MotoTokyo
      - bundle_data:/usr/local/bundle:cached
      - /MotoTokyo/node_modules
      - /app/vendor
      - /app/tmp
      - /app/log
      - puma_sockets:/MotoTokyo/tmp/sockets
    environment:
      RAILS_ENV: production
      TZ: Asia/Tokyo
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/MotoTokyo
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../certs:/etc/letsencrypt  # SSL証明書ディレクトリは永続化のためホストにマウント
      - ../certbot:/var/www/certbot  # Certbotのウェブルートディレクトリも永続化のためホストにマウント
      - puma_sockets:/MotoTokyo/tmp/sockets
    depends_on:
      - web
volumes:
  mysql_data:
  bundle_data:
  puma_sockets: