version: '3'
services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - .:/MotoTokyo
      - bundle_data:/usr/local/bundle:cached
      - /MotoTokyo/node_modules
      - /app/vendor
      - /app/tmp
      - /app/log
      - /app/.git
    environment:
      TZ: Asia/Tokyo
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub
    ports:
      - "3000:3000"
    depends_on:
      - db
      - chrome
  chrome:
    image: seleniarm/standalone-chromium:latest
    shm_size: 528m
    ports:
      - 4444:4444
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: db_moto_tokyo_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: Asia/Tokyo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  postgres_data:
  bundle_data: