default: &default
  adapter: postgis
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres
  password: password

development:
  <<: *default
  database: moto_tokyo_development

test:
  <<: *default
  database: moto_tokyo_test

production:
  <<: *default
  database: <%= Rails.application.credentials.rds[:database] %>
  username: <%= Rails.application.credentials.rds[:username] %>
  password: <%= Rails.application.credentials.rds[:password] %>
  host: <%= Rails.application.credentials.rds[:host] %>
  port: <%= Rails.application.credentials.rds[:port] %>
